#!/bin/bash

set -euo pipefail

__main() {
  unset -f __main

  local filename=
  filename=./notes/$(openssl rand -hex 4).md

  touch "$filename"
  printf -- '%s\n' "$filename"
}
__main "$@"

# vim:list:ts=2
