#!/bin/bash

set -euo pipefail

__main() {
  unset -f __main

  local listfile=
  listfile="$(mktemp)"

  for note in $(git ls-files ./notes ':!:./notes/README.md')
  do
    printf -- '%s:%s\n' $(git log --pretty='format:%at' --reverse "$note" | head -1) "$note"
  done | sort --numeric-sort --reverse > "$listfile"

  {
    printf -- '%s\n\n' '# index'

    for note in $(awk -F : '{ print $2 }' < "$listfile")
    do
      printf -- '- [%s](%s)\n' "$(head -n 1 "$note" | sed -e 's/^# *//')" "${note##notes/}"
    done
  } > ./notes/README.md
}
__main "$@"

# vim:list:ts=2
